In [1]:
import pandas as pd
# importing numpy as np
import numpy as np

In [2]:
df2 = pd.read_csv('C:\\Users\\fiona.havelock\\Documents\\FinalProject\\dft-road-casualty-statistics-casualty-1979-2021.csv')

C:\Users\fiona.havelock\AppData\Local\Temp\ipykernel_17796\2488291812.py:1: DtypeWarning: Columns (0,2,18) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv('C:\\Users\\fiona.havelock\\Documents\\FinalProject\\dft-road-casualty-statistics-casualty-1979-2021.csv')

In [4]:
#df2.head()

In [3]:
df = pd.read_csv('./dftRoadCasualtyStatisticsAccident19792021.csv')

KeyboardInterrupt:

In [5]:
#df.head()

In [6]:
accident = df2.merge(df, on = ['accident_index', 'accident_year', 'accident_reference'], how = 'left')
accident.head()

,accident_index,accident_year,accident_reference,vehicle_reference,casualty_reference,casualty_class,sex_of_casualty,age_of_casualty,age_band_of_casualty,casualty_severity,...,pedestrian_crossing_physical_facilities,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location
0,197901A11AD14,1979,01A11AD14,2,1,1,1,-1,-1,3,...,-1.0,1.0,8.0,1.0,-1.0,0.0,-1.0,-1.0,-1.0,-1
1,197901A1BAW34,1979,01A1BAW34,1,1,3,2,27,6,3,...,-1.0,4.0,8.0,3.0,-1.0,0.0,-1.0,-1.0,-1.0,-1
2,197901A1BFD77,1979,01A1BFD77,1,1,1,1,21,5,3,...,-1.0,4.0,8.0,3.0,-1.0,0.0,-1.0,-1.0,-1.0,-1
3,197901A1BFD77,1979,01A1BFD77,1,2,2,1,20,4,3,...,-1.0,4.0,8.0,3.0,-1.0,0.0,-1.0,-1.0,-1.0,-1
4,197901A1BFD77,1979,01A1BFD77,2,3,1,1,35,6,3,...,-1.0,4.0,8.0,3.0,-1.0,0.0,-1.0,-1.0,-1.0,-1

In [7]:
accident = accident.dropna()
accident

,accident_index,accident_year,accident_reference,vehicle_reference,casualty_reference,casualty_class,sex_of_casualty,age_of_casualty,age_band_of_casualty,casualty_severity,...,pedestrian_crossing_physical_facilities,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location
6436733,1999010SU0945,1999,010SU0945,1,1,1,2,21,5,3,...,0.0,1.0,4.0,1.0,0.0,0.0,2.0,1.0,1.0,E01023583
6436734,1999010SU0946,1999,010SU0946,2,1,1,1,57,9,3,...,0.0,6.0,4.0,1.0,0.0,0.0,2.0,1.0,1.0,E01023584
6436735,1999010SU0947,1999,010SU0947,2,1,2,1,46,8,3,...,0.0,4.0,1.0,2.0,0.0,0.0,2.0,1.0,1.0,E01023583
6436736,1999010SU0947,1999,010SU0947,2,2,2,2,36,7,3,...,0.0,4.0,1.0,2.0,0.0,0.0,2.0,1.0,1.0,E01023583
6436737,1999010SU0948,1999,010SU0948,1,1,1,1,20,4,2,...,0.0,6.0,1.0,1.0,0.0,0.0,2.0,1.0,1.0,E01023583
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11577516,2021991196607,2021,991196607,1,1,1,1,38,7,3,...,0.0,6.0,1.0,1.0,0.0,0.0,2.0,1.0,-1.0,-1
11577517,2021991196607,2021,991196607,2,2,1,1,61,9,3,...,0.0,6.0,1.0,1.0,0.0,0.0,2.0,1.0,-1.0,-1
11577518,2021991197944,2021,991197944,1,1,2,2,11,3,3,...,0.0,1.0,1.0,1.0,0.0,0.0,2.0,1.0,-1.0,-1
11577519,2021991200639,2021,991200639,1,1,3,2,34,6,3,...,5.0,1.0,9.0,1.0,0.0,0.0,1.0,2.0,-1.0,-1
11577520,2021991201030,2021,991201030,2,1,1,1,58,9,3,...,0.0,1.0,1.0,1.0,4.0,0.0,2.0,1.0,-1.0,-1

In [8]:
#accident.info()

In [8]:
accident = accident.drop(['accident_reference', 'first_road_number', 'first_road_class', 'accident_reference',  'second_road_number', 'vehicle_reference',
'second_road_class', 'lsoa_of_accident_location', 'sex_of_casualty', 'age_of_casualty', 'age_band_of_casualty', 'pedestrian_location', 
'pedestrian_movement', 'bus_or_coach_passenger', 'pedestrian_road_maintenance_worker', 'casualty_home_area_type', 'casualty_imd_decile', 'lsoa_of_casualty', 'trunk_road_flag', 'did_police_officer_attend_scene_of_accident'], axis = 1)

In [9]:
accident = accident[accident['accident_year']> 2004]  
accident

,accident_index,accident_year,casualty_reference,casualty_class,casualty_severity,car_passenger,casualty_type,location_easting_osgr,location_northing_osgr,longitude,...,junction_detail,junction_control,pedestrian_crossing_human_control,pedestrian_crossing_physical_facilities,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area
8264687,200501BS00001,2005,1,3,2,0,0,525680.0,178240.0,-0.191170,...,0.0,-1.0,0.0,1.0,1.0,2.0,2.0,0.0,0.0,1.0
8264688,200501BS00002,2005,1,2,3,0,11,524170.0,181650.0,-0.211708,...,6.0,2.0,0.0,5.0,4.0,1.0,1.0,0.0,0.0,1.0
8264689,200501BS00003,2005,1,1,3,0,9,524520.0,182240.0,-0.206458,...,0.0,-1.0,0.0,0.0,4.0,1.0,1.0,0.0,0.0,1.0
8264690,200501BS00004,2005,1,3,3,0,0,526900.0,177530.0,-0.173862,...,0.0,-1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0
8264691,200501BS00005,2005,1,1,3,0,3,528060.0,179040.0,-0.156618,...,0.0,-1.0,0.0,0.0,7.0,1.0,2.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11577516,2021991196607,2021,1,1,3,0,9,271195.0,558271.0,-4.010304,...,0.0,-1.0,0.0,0.0,6.0,1.0,1.0,0.0,0.0,2.0
11577517,2021991196607,2021,2,1,3,0,9,271195.0,558271.0,-4.010304,...,0.0,-1.0,0.0,0.0,6.0,1.0,1.0,0.0,0.0,2.0
11577518,2021991197944,2021,1,2,3,2,9,357297.0,860768.0,-2.716825,...,9.0,3.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,2.0
11577519,2021991200639,2021,1,3,3,0,0,326936.0,675925.0,-3.172192,...,3.0,2.0,0.0,5.0,1.0,9.0,1.0,0.0,0.0,1.0
11577520,2021991201030,2021,1,1,3,0,17,270574.0,556367.0,-4.019126,...,0.0,-1.0,0.0,0.0,1.0,1.0,1.0,4.0,0.0,2.0

In [10]:
LondonAccidents = accident.loc[accident['local_authority_ons_district'].isin(['E09000001', 'E09000002', 'E09000003', 'E09000004', 
'E09000005', 'E09000006', 'E09000007', 'E09000008', 'E09000009', 'E09000010', 'E09000011', 'E09000012', 'E09000013', 'E09000014', 
'E09000015', 'E09000016', 'E09000017', 'E09000018', 'E09000019', 'E09000020', 'E09000021', 'E09000022', 'E09000023', 'E09000024', 'E09000025', 'E09000026'
'E09000027', 'E09000028', 'E09000029', 'E09000030', 'E09000031', 'E09000032', 'E09000033' ])]
LondonAccidents

,accident_index,accident_year,casualty_reference,casualty_class,casualty_severity,car_passenger,casualty_type,location_easting_osgr,location_northing_osgr,longitude,...,junction_detail,junction_control,pedestrian_crossing_human_control,pedestrian_crossing_physical_facilities,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area
8264687,200501BS00001,2005,1,3,2,0,0,525680.0,178240.0,-0.191170,...,0.0,-1.0,0.0,1.0,1.0,2.0,2.0,0.0,0.0,1.0
8264688,200501BS00002,2005,1,2,3,0,11,524170.0,181650.0,-0.211708,...,6.0,2.0,0.0,5.0,4.0,1.0,1.0,0.0,0.0,1.0
8264689,200501BS00003,2005,1,1,3,0,9,524520.0,182240.0,-0.206458,...,0.0,-1.0,0.0,0.0,4.0,1.0,1.0,0.0,0.0,1.0
8264690,200501BS00004,2005,1,3,3,0,0,526900.0,177530.0,-0.173862,...,0.0,-1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0
8264691,200501BS00005,2005,1,1,3,0,3,528060.0,179040.0,-0.156618,...,0.0,-1.0,0.0,0.0,7.0,1.0,2.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11557028,2021481153885,2021,1,2,3,2,8,532307.0,181385.0,-0.094589,...,3.0,4.0,0.0,0.0,4.0,1.0,1.0,0.0,0.0,1.0
11557029,2021481153891,2021,1,1,3,0,1,533203.0,181439.0,-0.081663,...,6.0,2.0,0.0,5.0,4.0,1.0,1.0,0.0,0.0,1.0
11557030,2021481153896,2021,1,1,2,0,1,533034.0,180826.0,-0.084329,...,3.0,4.0,0.0,8.0,1.0,1.0,1.0,0.0,0.0,1.0
11557031,2021481153967,2021,1,1,3,0,1,532776.0,181424.0,-0.087819,...,3.0,4.0,0.0,0.0,4.0,1.0,1.0,0.0,0.0,1.0
11557032,2021481153971,2021,1,1,3,0,5,533809.0,180967.0,-0.073114,...,3.0,4.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0

In [14]:

df3 = pd.read_csv('C:\\Users\\fiona.havelock\\Documents\\FinalProject\\londonPopulation.csv')

In [15]:
accidentPopData = LondonAccidents.merge(df3, on = ['local_authority_ons_district'], how = 'left')
accidentPopData.head()

,accident_index,accident_year,casualty_reference,casualty_class,casualty_severity,car_passenger,casualty_type,location_easting_osgr,location_northing_osgr,longitude,...,pedestrian_crossing_human_control,pedestrian_crossing_physical_facilities,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area,district,population
0,200501BS00001,2005,1,3,2,0,0,525680.0,178240.0,-0.191170,...,0.0,1.0,1.0,2.0,2.0,0.0,0.0,1.0,Kensington and Chelsea,"143,940"
1,200501BS00002,2005,1,2,3,0,11,524170.0,181650.0,-0.211708,...,0.0,5.0,4.0,1.0,1.0,0.0,0.0,1.0,Kensington and Chelsea,"143,940"
2,200501BS00003,2005,1,1,3,0,9,524520.0,182240.0,-0.206458,...,0.0,0.0,4.0,1.0,1.0,0.0,0.0,1.0,Kensington and Chelsea,"143,940"
3,200501BS00004,2005,1,3,3,0,0,526900.0,177530.0,-0.173862,...,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,Kensington and Chelsea,"143,940"
4,200501BS00005,2005,1,1,3,0,3,528060.0,179040.0,-0.156618,...,0.0,0.0,7.0,1.0,2.0,0.0,0.0,1.0,Kensington and Chelsea,"143,940"

In [16]:
accidentPopData.to_csv('./accidentPopData.csv', index=False)

In [17]:
accidentPopData['date'].head()

0    04/01/2005
1    05/01/2005
2    06/01/2005
3    07/01/2005
4    10/01/2005
Name: date, dtype: object

In [12]:
LondonAccidents.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 401446 entries, 8264687 to 11557032
Data columns (total 33 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   accident_index                           401446 non-null  object
 1   accident_year                            401446 non-null  int64
 2   casualty_reference                       401446 non-null  int64
 3   casualty_class                           401446 non-null  int64
 4   casualty_severity                        401446 non-null  int64
 5   car_passenger                            401446 non-null  int64
 6   casualty_type                            401446 non-null  int64
 7   location_easting_osgr                    401446 non-null  float64
 8   location_northing_osgr                   401446 non-null  float64
 9   longitude                                401446 non-null  float64
 10  latitude                                 401446 non-null  float64
 11  police_force                             401446 non-null  float64
 12  accident_severity                        401446 non-null  float64
 13  number_of_vehicles                       401446 non-null  float64
 14  number_of_casualties                     401446 non-null  float64
 15  date                                     401446 non-null  object
 16  day_of_week                              401446 non-null  float64
 17  time                                     401446 non-null  object
 18  local_authority_district                 401446 non-null  float64
 19  local_authority_ons_district             401446 non-null  object
 20  local_authority_highway                  401446 non-null  object
 21  road_type                                401446 non-null  float64
 22  speed_limit                              401446 non-null  float64
 23  junction_detail                          401446 non-null  float64
 24  junction_control                         401446 non-null  float64
 25  pedestrian_crossing_human_control        401446 non-null  float64
 26  pedestrian_crossing_physical_facilities  401446 non-null  float64
 27  light_conditions                         401446 non-null  float64
 28  weather_conditions                       401446 non-null  float64
 29  road_surface_conditions                  401446 non-null  float64
 30  special_conditions_at_site               401446 non-null  float64
 31  carriageway_hazards                      401446 non-null  float64
 32  urban_or_rural_area                      401446 non-null  float64
dtypes: float64(22), int64(6), object(5)
memory usage: 104.1+ MB

In [ ]:
df = pd.read_csv('./dftRoadCasualtyStatisticsAccident19792021.csv')

In [ ]:
local_authority_ons_district

In [18]:

hours = []

for ele in LondonAccidents['time'].values:
    hour = ele.split(':')
    hours.append(int(hour[0]))
    #print(hours)
    
LondonAccidents["hour"] = hours
LondonAccidents = LondonAccidents.drop(['time'], axis=1)

C:\Users\fiona.havelock\AppData\Local\Temp\ipykernel_23940\2330034180.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  LondonAccidents["hour"] = hours

In [20]:
months = []

for ele in LondonAccidents['date'].values:
    month = ele.split('/')
    months.append(int(month[1]))
    #print(hours)
    
LondonAccidents["month"] = months
LondonAccidents = LondonAccidents.drop(['date'], axis=1)

In [22]:
LondonAccidents.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 401446 entries, 8264687 to 11557032
Data columns (total 33 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   accident_index                           401446 non-null  object
 1   accident_year                            401446 non-null  int64
 2   casualty_reference                       401446 non-null  int64
 3   casualty_class                           401446 non-null  int64
 4   casualty_severity                        401446 non-null  int64
 5   car_passenger                            401446 non-null  int64
 6   casualty_type                            401446 non-null  int64
 7   location_easting_osgr                    401446 non-null  float64
 8   location_northing_osgr                   401446 non-null  float64
 9   longitude                                401446 non-null  float64
 10  latitude                                 401446 non-null  float64
 11  police_force                             401446 non-null  float64
 12  accident_severity                        401446 non-null  float64
 13  number_of_vehicles                       401446 non-null  float64
 14  number_of_casualties                     401446 non-null  float64
 15  day_of_week                              401446 non-null  float64
 16  local_authority_district                 401446 non-null  float64
 17  local_authority_ons_district             401446 non-null  object
 18  local_authority_highway                  401446 non-null  object
 19  road_type                                401446 non-null  float64
 20  speed_limit                              401446 non-null  float64
 21  junction_detail                          401446 non-null  float64
 22  junction_control                         401446 non-null  float64
 23  pedestrian_crossing_human_control        401446 non-null  float64
 24  pedestrian_crossing_physical_facilities  401446 non-null  float64
 25  light_conditions                         401446 non-null  float64
 26  weather_conditions                       401446 non-null  float64
 27  road_surface_conditions                  401446 non-null  float64
 28  special_conditions_at_site               401446 non-null  float64
 29  carriageway_hazards                      401446 non-null  float64
 30  urban_or_rural_area                      401446 non-null  float64
 31  hour                                     401446 non-null  int64
 32  month                                    401446 non-null  int64
dtypes: float64(22), int64(8), object(3)
memory usage: 104.1+ MB

In [24]:
HotspotData = LondonAccidents.drop(['accident_index', 'casualty_reference', 'accident_year', 'car_passenger', 'location_northing_osgr', 'location_easting_osgr',
'local_authority_ons_district', 'local_authority_highway','junction_control', 'junction_detail', 'pedestrian_crossing_human_control', 'pedestrian_crossing_physical_facilities', 
'special_conditions_at_site'  ], axis=1)

In [25]:
HotspotData.head()

,casualty_class,casualty_severity,casualty_type,longitude,latitude,police_force,accident_severity,number_of_vehicles,number_of_casualties,day_of_week,local_authority_district,road_type,speed_limit,light_conditions,weather_conditions,road_surface_conditions,carriageway_hazards,urban_or_rural_area,hour,month
8264687,3,2,0,-0.191170,51.489096,1.0,2.0,1.0,1.0,3.0,12.0,6.0,30.0,1.0,2.0,2.0,0.0,1.0,17,1
8264688,2,3,11,-0.211708,51.520075,1.0,3.0,1.0,1.0,4.0,12.0,3.0,30.0,4.0,1.0,1.0,0.0,1.0,17,1
8264689,1,3,9,-0.206458,51.525301,1.0,3.0,2.0,1.0,5.0,12.0,6.0,30.0,4.0,1.0,1.0,0.0,1.0,0,1
8264690,3,3,0,-0.173862,51.482442,1.0,3.0,1.0,1.0,6.0,12.0,6.0,30.0,1.0,1.0,1.0,0.0,1.0,10,1
8264691,1,3,3,-0.156618,51.495752,1.0,3.0,1.0,1.0,2.0,12.0,6.0,30.0,7.0,1.0,2.0,0.0,1.0,21,1

In [27]:
severeFatalAccidents = HotspotData[HotspotData['accident_severity']<3]  
severeFatalAccidents.head()

,casualty_class,casualty_severity,casualty_type,longitude,latitude,police_force,accident_severity,number_of_vehicles,number_of_casualties,day_of_week,local_authority_district,road_type,speed_limit,light_conditions,weather_conditions,road_surface_conditions,carriageway_hazards,urban_or_rural_area,hour,month
8264687,3,2,0,-0.191170,51.489096,1.0,2.0,1.0,1.0,3.0,12.0,6.0,30.0,1.0,2.0,2.0,0.0,1.0,17,1
8264710,1,2,5,-0.205139,51.500191,1.0,2.0,2.0,1.0,5.0,12.0,6.0,30.0,4.0,1.0,1.0,0.0,1.0,0,1
8264713,3,2,0,-0.174925,51.495498,1.0,2.0,1.0,1.0,7.0,12.0,6.0,30.0,4.0,1.0,1.0,0.0,1.0,3,1
8264725,1,3,3,-0.215545,51.517796,1.0,2.0,2.0,2.0,3.0,12.0,2.0,30.0,4.0,2.0,2.0,0.0,1.0,17,2
8264726,1,2,5,-0.215545,51.517796,1.0,2.0,2.0,2.0,3.0,12.0,2.0,30.0,4.0,2.0,2.0,0.0,1.0,17,2

In [29]:
severeFatalAccidents.to_csv('./severeFatalAccidents.csv', index=False)

In [28]:
slightAccidents = HotspotData[HotspotData['accident_severity']==3]  
slightAccidents.head()

,casualty_class,casualty_severity,casualty_type,longitude,latitude,police_force,accident_severity,number_of_vehicles,number_of_casualties,day_of_week,local_authority_district,road_type,speed_limit,light_conditions,weather_conditions,road_surface_conditions,carriageway_hazards,urban_or_rural_area,hour,month
8264688,2,3,11,-0.211708,51.520075,1.0,3.0,1.0,1.0,4.0,12.0,3.0,30.0,4.0,1.0,1.0,0.0,1.0,17,1
8264689,1,3,9,-0.206458,51.525301,1.0,3.0,2.0,1.0,5.0,12.0,6.0,30.0,4.0,1.0,1.0,0.0,1.0,0,1
8264690,3,3,0,-0.173862,51.482442,1.0,3.0,1.0,1.0,6.0,12.0,6.0,30.0,1.0,1.0,1.0,0.0,1.0,10,1
8264691,1,3,3,-0.156618,51.495752,1.0,3.0,1.0,1.0,2.0,12.0,6.0,30.0,7.0,1.0,2.0,0.0,1.0,21,1
8264692,1,3,3,-0.203238,51.515540,1.0,3.0,2.0,1.0,3.0,12.0,6.0,30.0,1.0,2.0,2.0,0.0,1.0,12,1

In [30]:
slightAccidents.to_csv('/slightAccidents.csv', index=False)

In [ ]:
E09000001	City of London
E09000001	City of London
E09000002	Barking and Dagenham
E09000003	Barnet
E09000004	Bexley
E09000005	Brent
E09000006	Bromley
E09000007	Camden
E09000008	Croydon
E09000009	Ealing
E09000010	Enfield
E09000011	Greenwich
E09000012	Hackney
E09000013	Hammersmith and Fulham
E09000014	Haringey
E09000015	Harrow
E09000016	Havering
E09000017	Hillingdon
E09000018	Hounslow
E09000019	Islington
E09000020	Kensington and Chelsea
E09000021	Kingston upon Thames
E09000022	Lambeth
E09000023	Lewisham
E09000024	Merton
E09000025	Newham
E09000026	Redbridge
E09000027	Richmond upon Thames
E09000028	Southwark
E09000029	Sutton
E09000030	Tower Hamlets
E09000031	Waltham Forest
E09000032	Wandsworth
E09000033	Westminster

In [46]:
LondonAccidentsCluster = accident.loc[accident['local_authority_ons_district'].isin(['E09000001', 'E09000002', 'E09000003', 'E09000004', 
'E09000005', 'E09000006', 'E09000007', 'E09000008', 'E09000009', 'E09000010', 'E09000011', 'E09000012', 'E09000013', 'E09000014', 
'E09000015', 'E09000016', 'E09000017', 'E09000018', 'E09000019', 'E09000020', 'E09000021', 'E09000022', 'E09000023', 'E09000024', 'E09000025', 'E09000026'
'E09000027', 'E09000028', 'E09000029', 'E09000030', 'E09000031', 'E09000032', 'E09000033' ])]
LondonAccidents

,accident_year,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,accident_severity,number_of_vehicles,number_of_casualties,day_of_week,...,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,hour,month
6224198,2005,525680.0,178240.0,-0.191170,51.489096,1,2,1,1,3,...,1,2,2,0,0,1,1,2,17,1
6224199,2005,524170.0,181650.0,-0.211708,51.520075,1,3,1,1,4,...,4,1,1,0,0,1,1,2,17,1
6224200,2005,524520.0,182240.0,-0.206458,51.525301,1,3,2,1,5,...,4,1,1,0,0,1,1,2,0,1
6224201,2005,526900.0,177530.0,-0.173862,51.482442,1,3,1,1,6,...,1,1,1,0,0,1,1,2,10,1
6224202,2005,528060.0,179040.0,-0.156618,51.495752,1,3,1,1,2,...,7,1,2,0,0,1,1,2,21,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688254,2021,532307.0,181385.0,-0.094589,51.515904,48,3,1,1,1,...,4,1,1,0,0,1,3,2,3,10
8688255,2021,533203.0,181439.0,-0.081663,51.516179,48,3,2,1,4,...,4,1,1,0,0,1,1,2,21,11
8688256,2021,533034.0,180826.0,-0.084329,51.510710,48,2,2,1,3,...,1,1,1,0,0,1,1,2,9,11
8688257,2021,532776.0,181424.0,-0.087819,51.516144,48,3,2,1,5,...,4,1,1,0,0,1,1,2,18,12
8688258,2021,533809.0,180967.0,-0.073114,51.511794,48,3,2,1,5,...,1,1,1,0,0,1,1,2,13,12

In [6]:
for col in df.columns:
    if 'E09000020' in df[col].values:
        print(col)

local_authority_highway

C:\Users\fiona.havelock\AppData\Local\Temp\ipykernel_15688\3368249836.py:2: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if 'E09000020' in df[col].values:

In [ ]:
road_type	1	Roundabout
road_type	2	One way street
road_type	3	Dual carriageway
road_type	6	Single carriageway
road_type	7	Slip road
road_type	9	Unknown
road_type	12	One way street/Slip road
road_type	-1	Data missing or out of range